permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 禹墨
  email: disheng54@163.com
  link: http://disheng54.github.io
  weibo: http://weibo.com
  github: https://github.com/disheng54

# 站点信息
title: 禹墨的博客 
description: 禹墨的博客
url: http://disheng54.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yumo.qiniudn.com/baby.png
favicon: http://yumo.qiniudn.com/baby.png

# google analytics 设置
ga:
  id: 
  url: http://disheng54.github.io

# disqus 设置
disqus:
  shortname: yumo-zh

# 主题设置，自动激活某个标签
active: android

# 首页除了最新文章外显示分类
cates: 
  - andorid

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
